# Generated by Django 5.1 on 2024-09-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produto_exibirhomee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='exibirHomee',
        ),
    ]
